runner:
  total_steps: 20000
  gradient_clipping: 5
  gradient_accumulate_steps: 8

  log_step: 100
  eval_step: 500
  save_step: 500
  max_keep: 1
  eval_dataloaders:
    - dev

optimizer:
  name: Adam
  lr: 1.0e-5

# comment the whole scheduler config block
# to disable learning rate scheduling
scheduler:
  name: linear_schedule_with_warmup
  num_warmup_steps: 500

downstream_expert:
  datarc:
    num_workers: 8
    train_batch_size: 4
    eval_batch_size: 4
    voiceMOS_path: /livingrooms/wiz94156/voiceMOS/phase1-main/DATA

  modelrc:
    projector_dim: 256
    objective: MSELoss
    pooling_name: MeanPooling
